a=0
while a!=30:   
    x = input('成績:')
    r = input('成績:')
    v = input('成績:')
    p = input('成績:')
    q = input('成績:')
    w = input('成績:')
    e = input('成績:')
    i = input('成績:')
    n = input('成績:')
    m = input('成績:')
    c = input('成績:')
    x=int(x)
    r=int(r)
    v=int(v)
    p=int(p)
    q=int(q)
    w=int(w)
    e=int(e)
    i=int(i)
    n=int(n)
    m=int(m)
    c=int(c)
    b=x+r+v+p+q+w+e+i+n+m+c
    b=b/11
    print('總成績',b)
    a=a+1